### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by Tastaturberuf** [Tastaturberuf/anyStores#50]
Warning: Missing argument 2 for Tastaturberuf\AnyStoresHooks::getSearchablePages(), called in .../htdocs/system/modules/core/classes/RebuildIndex.php on line 74 and defined in system/modules/anyStores/classes/AnyStoresHooks.php on line 213
#0 system/modules/anyStores/classes/AnyStoresHooks.php(213): __error(2, 'Missing argumen...', '/mnt/webl/d1/53...', 213, Array)
#1 system/modules/core/classes/RebuildIndex.php(74): Tastaturberuf\AnyStoresHooks->getSearchablePages(Array)
#2 system/modules/core/modules/ModuleMaintenance.php(51): Contao\RebuildIndex->run()
#3 system/modules/core/classes/BackendModule.php(91): Contao\ModuleMaintenance->compile()
#4 system/modules/core/classes/Backend.php(262): Contao\BackendModule->generate()
#5 contao/main.php(137): Contao\Backend->getBackendModule('maintenance')
#6 contao/main.php(288): Main->run()
#7 {main}

**Comment by Tastaturberuf** [comment]
Fixed in 1.8.0
